### ISSUE TITLE
get_transaction error: ArgumentError (no time information in ""):

### ISSUE THREAD

**Issue by roysim** [tylerhunt/remit#10]
I get a parsing error when I try to call get_transaction:

Code:
    logger.info "Transaction ID = " + transactionID
    transaction_status_request = Remit::GetTransactionStatus::Request.new(:transaction_id=>transactionID)
    transaction_status = @remit_api.get_transaction(transaction_status_request)

Result:
Transaction ID = 15TULGBA47T43B8F6LUMK9GQ32AHGBK12D5

ArgumentError (no time information in ""):
/opt/local/lib/ruby1.9/1.9.1/time.rb:263:in `parse'
relax (0.0.7) lib/relax/parsers/hpricot.rb:115:in`time_value'
relax (0.0.7) lib/relax/parsers/hpricot.rb:43:in `block in parse!'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in`each'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in `parse!'
relax (0.0.7) lib/relax/parsers/base.rb:10:in`initialize'
relax (0.0.7) lib/relax/parsers/hpricot.rb:12:in `initialize'
relax (0.0.7) lib/relax/response.rb:17:in`new'
relax (0.0.7) lib/relax/response.rb:17:in `initialize'
relax (0.0.7) lib/relax/parsers/hpricot.rb:39:in`new'
relax (0.0.7) lib/relax/parsers/hpricot.rb:39:in `block in parse!'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in`each'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in `parse!'
relax (0.0.7) lib/relax/parsers/base.rb:10:in`initialize'
relax (0.0.7) lib/relax/parsers/hpricot.rb:12:in `initialize'
relax (0.0.7) lib/relax/response.rb:17:in`new'
relax (0.0.7) lib/relax/response.rb:17:in `initialize'
remit (2.0.1) lib/remit/common.rb:53:in`initialize'
relax (0.0.7) lib/relax/service.rb:74:in `new'
relax (0.0.7) lib/relax/service.rb:74:in`call'
remit (2.0.1) lib/remit/operations/get_transaction.rb:15:in `get_transaction'
app/controllers/private_lesson_bookings_controller.rb:302:in`payment_response'
internal:prelude:10:in `synchronize'

**Comment by roysim** [comment]
I should say that I have the same error if I use the following code
`logger.info "Transaction ID = " + transactionID
transaction_status_request = Remit::GetTransaction::Request.new(:transaction_id=>transactionID)
transaction_status = @remit_api.get_transaction(transaction_status_request)`

**Comment by roysim** [comment]
I fixed this by modifying remit's `class Transaction < BaseResponse`
to exclude `parameter :caller_transaction_date, :type => :time`

My code change is at https://github.com/roysim/remit/commit/a62af13fab7518ee9bf34205de3e6f562c352c5e

**Comment by jjb** [comment]
This should be reopened -- the system should be able to handle blank input.

The exception is coming from the relax library, when `Time.parse` is called on a blank string.

**Comment by jjb** [comment]
I should note: I only started having this problem when I switched from ruby 1.8.7 to 1.9.2 -- I don't yet know why that caused the problem.

**Comment by pboling** [comment]
We need to create an official fork of Relax for Remit.  Remit was written against an older Relax API, and if Remit was rewritten to use the new API it would entail a complete rewrite, and there is not much benefit to Remit in using the new Relax API.  Any volunteers to fork/rebrand relax so we can disentangle the project?

This fork has the most recent code that will work with Remit:
https://github.com/dbalatero/relax

**Comment by rchekaluk** [comment]
I see no change to this behavior when using these gems:

gem 'remit', '2.0.2', :git => 'https://github.com/rchekaluk/remit.git'
gem 'relax', :git => 'https://github.com/dbalatero/relax.git'

Am I missing something?

**Comment by pboling** [comment]
If you want to use remit you will need to get your hands dirty.  No maintainers actively use it on any projects.  Additional maintainers are welcome.  The released version of relax that works best with remit is 0.7.1, IIRC.
