### ISSUE TITLE
Remit::API#pay returns "Developer account is needed to make API calls"

### ISSUE THREAD

**Issue by bryan-liff** [tylerhunt/remit#13]
I am using Remit 2.0.2 and am unable to collect [user] authorized payments via API call. The Amazon CBUI cycle is working as expected. 

Everything works perfectly in development and staging, but when I try it from production I receive the error message.

AmazonFps#collect is being called from:
http://pastie.org/private/detg59ldwfszw2wqztu9a

And the output: (@access_key & @secret_key removed)
http://pastie.org/private/qh0sidywabbvni7tevop0a

If all looks good on the Remit end, how would I extract the actual REST request URL and XML for the request in order to troubleshoot with Amazon directly?

Thanks!!!

**Comment by pboling** [comment]
Reading through your Pastie (and adding some formatting):

```
<Response>
  <Errors>
    <Error>
      <Code>AccessFailure</Code>
      <Message>Developer account is needed to make API calls.</Message>
    </Error>
  </Errors>
  <RequestID>301e1bf8-502d-4426-8163-a33196c5f5d9</RequestID>
</Response>
```

I take that to mean that you do not have your production access key and secret keys setup?

**Comment by bryan-liff** [comment]
Yes we do have the production access & secret keys setup.

I am trying to ascertain whether the problem is with Remit or Amazon FPS. I suspect it is with Amazon but in order to troubleshoot it with them, I need to see the raw request data. 

What would be the best way to do that? Are there any debugging settings or do I have to start putting logging calls in the gem code?

**Comment by pboling** [comment]
I just looked briefly, and it does not appear that we have debugging setting in Remit yet.  They would be a welcome addition.

Alternatively, you could add integration specs (with live calls to Amazon) for what you are trying to do, and in so doing export the request and response.  See current integration specs for examples.

**Comment by pboling** [comment]
If you go the testing route:

Running Specification Suite

Copy test.sh.example to test.sh
Edit test.sh to have valid Amazon developer account access and secret keys
Run ./test.sh from the command line.

**Comment by bryan-liff** [comment]
Sounds good Peter - I'll fork it and try adding those specs this week.

Cheers and thanks for your help!

Bryan Liff
Minerva Group PSC http://minerva-group.com
+1 (212) 901-5252 x121

http://minerva-group.com

**Comment by pboling** [comment]
Did you ever resolve this issue?

**Comment by bryan-liff** [comment]
Hey Peter,

Sorry about not getting back to you. The short answer is no, I didn't get a
chance to do it.

The long answer is, no I didn't get a chance to do it because, as it turns
out, the problem was based on the fact that Amazon was blocking our
transactions for some bass ackward internal regulation they have, so we had
to end up going with PayPal instead.

Bryan Liff
Minerva Group PSC http://minerva-group.com
+1 (212) 901-5252 x121

http://minerva-group.com

On Wed, Dec 14, 2011 at 10:27 AM, Peter Boling <
reply@reply.github.com

**Comment by pboling** [comment]
Interesting.  I'll close this issue then.  I hope Paypal treats you better!
