### ISSUE TITLE
Problem with validation

### ISSUE THREAD

**Issue by cdunn2001** [tylerhunt/remit#4]
A really clear example of validation could be invaluable. I had to switch to the Amazon Perl code in order to understand what was going on.

Anyway, here is something I've had a problem with. I'll just show the encoded URL that I send to the verification API:

```
https://fps.sandbox.amazonaws.com/?Action=VerifySignature&Version=2008-09-17&UrlEndPoint=http%3A%2F%2Flocalhost%3A3001%2Faccount%2Fvalidateamazon&HttpParameters=signatureMethod%3DRSA-SHA1%26expiry%3D07%252F2016%26callerReference%3D668%26tokenID%3D61UNRIMJNVQKK4568LE17TTAFXECG1HG8SR4HHPUPQ7FR2UX3KQT2U4ZFKZNE3N4%26signatureVersion%3D2%26status%3DSC%26signature%3DLp58dpM4C01f4q6MR6nIhOddTyRPEN8BWqsNKvxag4y1nvOIme0tpKXdRbXy3x3nbTjO4Hc7tCTj%250Acyiacy3ddeGySB2Py%252B3wlIZnh3BUTqBovBhspWX6jSPwxyhX8xmOjB5lkFeojrfXlZNPMJBo%252FvQs%250A4cQFJWNmZp%252BPruXu6DU%253D%26certificateUrl%3Dhttps%253A%252F%252Ffps.sandbox.amazonaws.com%252Fcerts%252F090910%252FPKICert.pem%253FrequestId%253Dbjzk5q4cl91bw4y8k1g37sak4mobdz53icxh3u5f1lbncs7y7g0
```

If you copy that into a browser, you'll get this:

```
InvalidParamshttp://localhost:3001/account/validateamazon is an invalid URLc85cfe8c-0049-41bf-9730-7f5d59d1cb7b
```

The signature might be valid, but the API refuses to validate because of my localhost URL. Therefore, it's not always simply an 'invalid signature'. We need a way to see the response, rather than just 1 or 0 from `Remit::InboundRequest#valid?`, _e.g._

Could I suggest `InboundRequest#invalid?`? That could return `false` on success, or a string on error.

**Comment by pboling** [comment]
The best available examples of VerifySignature are in the integration specs in the project.  I will be spending some time on this code soon, and will look at making the result more useful.

**Comment by pboling** [comment]
The test that shows correct usage is the last one in the file here:
https://github.com/tylerhunt/remit/blob/master/spec/integrations/verify_signature_spec.rb

It says 'invalid params' in the test name because the default params hash provided by rails is invalid if passed back to Amazon, since the action, controller and id params are inserted into the request by rails.  The params must be cleaned before being sent back to Amazon for verification.

It shows you how to get the inherently incorrect rails params to pass VerifySignature with Amazon.

**Comment by cdunn2001** [comment]
> test that shows correct usage

Yes, `verify_signature_spec.rb` is pretty helpful. That's where I looked to write my code in the first place. You're referring to this:
    @remit ||= Remit::API.new(access_key, seret_key, true)
    ...
    Remit::PipelineResponse.new("#{@url.scheme}://#{@url.host}#{@url.path}", @parameters, remit, {:skip_param_keys => ['action','controller','id']}).valid?

However, with signature version v2, the access-key & secret-key are no longer needed. That's good, since I'd rather not post those. But I think the API needs to be altered. E.g.:
    @api ||= Remit::VerifySignatureAPI.new(true)
    ...
    Remit::PipelineResponse.new("#{@url.scheme}://#{@url.host}#{@url.path}", @parameters, api, {:skip_param_keys => ['action','controller','id']}).valid?

> the default params hash provided by rails is invalid

My original example (not here, since I edited the original -- sorry) did not contain any Rails parameters, but I tried again with `:skip_param_keys` and got the same result: `false`.

The URL I posted earlier does not use any of the Rails parameters. As you can see, the response  also says, `... is an invalid URL`. When I contact FPS anew, with `127.0.0.1` in the return URL, to set-up a new recurring payment, I get a valid signature. E.g., added into a query-string to the verification API (and you can test this in your own browser):

```
https://fps.sandbox.amazonaws.com/?Action=VerifySignature&Version=2008-09-17&UrlEndPoint=http%3A%2F%2F127.0.0.1%3A3001%2Faccount%2Fvalidateamazon&HttpParameters=signatureMethod%3DRSA-SHA1%26expiry%3D07%252F2016%26callerReference%3D669%26tokenID%3D63UNGI6JN3QKK426ALEP7ZTARX1CGEH38S84RHP5PB7FU2SX3JQT2UHZPKZZEJNT%26signatureVersion%3D2%26status%3DSC%26signature%3Dq%252F6Di1gSG%252FMJ%252FwiaAQQzKXWVo%252BQmRB2FQ4Bq6kRyhnMS93SUAH0sNwiwhLKzeemXScsoTM9d3iDe%250A%252FEU%252FTqWZ%252FNhCfIGd5%252BeB00eTMhZJgoA92bJZbMNIWY9VuEA%252FyDm%252FSzPB%252BoFy6ZJin150wLizv%252BTr%250AXZgy9VAxZoorqmJ3d8k%253D%26certificateUrl%3Dhttps%253A%252F%252Ffps.sandbox.amazonaws.com%252Fcerts%252F090910%252FPKICert.pem%253FrequestId%253Dbjzk5q4cl91bw4y8k1g37sak4mobdz53icxh3u5f1lbncs7y7g2
```

which yields
    Successf6e79149-a442-4b65-ae16-770df09dd228:0
The only difference in how those were produced is `127.0.0.1` instead of `localhost`. (And note that both include a port number.) The signature from Amazon was completely valid in both cases.

So the message returned from Amazon's verification API really can be useful. It isn't just 'success' or 'failure'. Do you see what I mean now? In `inbound_request.rb`, we have only:
    result.verify_signature_result.verification_status == 'Success'

Maybe I'm fussing over a rarity. `invalid URL` might be the only special case. Still, I would like to be able to learn the URL that Remit is using to ping Amazon's signature verification API, and I'd like a way to make the call myself so that I can see the response.

I think that the attempt to continue supporting version1 signature-verification has shackled Remit, and that's the fault of Amazon, not of the authors of Remit. As [version1 will no longer be supported as of 30 January 2011](http://docs.amazonwebservices.com/AmazonFPS/2010-08-28/FPSAdvancedGuide/), maybe we should create a new Remit API to make things simpler, more transparent, and easier to debug. E.g.
    service = AmazonFPS.new(:sandbox => true)
    response = PipelineResponse.new(params)
    verify_response_signature_url = service.encode_url_for_verification_api(response)
    result = http_client.get(verify_response_signature_url)
    return result =~ /^Success/
I don't know. Something like that. Really, there should be two levels of API: a core, and a higher-level API written entirely in terms of the core. Kinda like git. That could make it easy to use, but also easy to debug.

That's just a suggestion. Remit has been enormously helpful to me already, and a obviously a huge amount of work has gone into it. Thanks.
