### ISSUE TITLE
GetTransactionStatus Operation doesn't work properly

### ISSUE THREAD

**Issue by rishav** [tylerhunt/remit#6]
The GetTransactionStatus operation has some issues. I mean it doesn't work at all. 

 there is no get_transaction_status method for the Remit::Api object, I think its not included in the class Remit/Api class definition.  While this actually exists in the operations folder

**Comment by ghost** [comment]
Use

pay_response = api.pay(request)
if pay_response.pay_result.transaction_status=="Success"
U'l get...
and if u know something about Ipn(instant payment notification) please send me a mail shajinvk@gmail.com

**Comment by rishav** [comment]
Well, sometimes the transaction status'es are pending, so  I need to fetch them and thats when its kinda gets a little messed up. I have to use GetTransaction operation instead of just status. I ll send out a pull request, if its I fix it. Not using ipns yet. 

Thanks

**Comment by iamtheschmitzer** [comment]
I've found a problem regarding this.  I have GetTransactionStatus working on my fork, but have not yet processed the response successfully.

**Comment by roysim** [comment]
@iamtheschmitzer, did you ever get GetTransactionStatus to work?  I have an issue with both GetTransaction and GetTransactionStatus.    (https://github.com/tylerhunt/remit/issues/10)

**Comment by iamtheschmitzer** [comment]
I dropped use of it in favor of GetTransaction because it had a limited set
of fields in its return set.

However, I think I did get it working, if I remember correctly.  Your
welcome to clone and try.

What is the issue with GetTransaction?

**Comment by roysim** [comment]
When I call get_transaction I always seem to get an error 
ArgumentError (no time information in ""): /opt/local/lib/ruby1.9/1.9.1/time.rb:263:in parse'

Do you not have that problem then?

**Comment by iamtheschmitzer** [comment]
No, get transaction has no error for me.

Is your error while sending the message, or processing the response?

**Comment by roysim** [comment]
My error comes when processing the response from get_transaction.  It fails parsing a missing time value in the response.

Code:
    logger.info "Transaction ID = " + transactionID  
    transaction_request = Remit::GetTransaction::Request.new(
    :transaction_id => transactionID 
    )
    transaction_response = @remit_api.get_transaction(transaction_request)

Error:
ArgumentError (no time information in ""):
/opt/local/lib/ruby1.9/1.9.1/time.rb:263:in `parse'
relax (0.0.7) lib/relax/parsers/hpricot.rb:115:in`time_value'
relax (0.0.7) lib/relax/parsers/hpricot.rb:43:in `block in parse!'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in`each'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in `parse!'
relax (0.0.7) lib/relax/parsers/base.rb:10:in`initialize'
relax (0.0.7) lib/relax/parsers/hpricot.rb:12:in `initialize'
relax (0.0.7) lib/relax/response.rb:17:in`new'
relax (0.0.7) lib/relax/response.rb:17:in `initialize'
relax (0.0.7) lib/relax/parsers/hpricot.rb:39:in`new'
relax (0.0.7) lib/relax/parsers/hpricot.rb:39:in `block in parse!'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in`each'
relax (0.0.7) lib/relax/parsers/hpricot.rb:17:in `parse!'
relax (0.0.7) lib/relax/parsers/base.rb:10:in`initialize'
relax (0.0.7) lib/relax/parsers/hpricot.rb:12:in `initialize'
relax (0.0.7) lib/relax/response.rb:17:in`new'
relax (0.0.7) lib/relax/response.rb:17:in `initialize'
remit (2.0.1) lib/remit/common.rb:53:in`initialize'
relax (0.0.7) lib/relax/service.rb:74:in `new'
relax (0.0.7) lib/relax/service.rb:74:in`call'
remit (2.0.1) lib/remit/operations/get_transaction.rb:15:in `get_transaction'
app/controllers/my_controller.rb:362:in`payment_response'
internal:prelude:10:in `synchronize'

**Comment by iamtheschmitzer** [comment]
Looks similar to mine, except I add a

if transaction_request.valid?
end

I see the following dates in the response:

DateReceived
DateCompleted
Date

They are all of the form "2011-04-15T04:51:29.105-07:00"

Not sure what to do, other than comment out parsing of the response in the
relax gem and log it.

jeff

**Comment by roysim** [comment]
Thanks.  I made a change to remit that fixed it.

In  class Transaction < BaseResponse
I commented out
parameter :caller_transaction_date, :type => :time

I don't see that parameter in the Amazon FPS spec.  Once I commented it out, there is no more error.

Not sure why it wasn't working in my case, but seems to work for other.

Thanks for your help.

**Comment by roysim** [comment]
Actually, it is likely that the reason I hit this issue and others have not is simply that I never passed a `:transaction_date` to my `reserve` and `settle` calls.  It is an optional parameter.  

That means the response didn't include any value in `caller_transaction_date`.  So the parsing of an empty string into a time failed.

**Comment by iamtheschmitzer** [comment]
Great to hear it is fixed

What is your site URL?

Jeff

**Comment by pboling** [comment]
The Amazon API specs have changed numerous times.  Remit only attempts to be compatible with the latest, but as that is a moving target we often get dead weight in the code.  If you would like to update any of the Remit APIs to match the latest FPS APIs, I will merge in pull requests.
