### ISSUE TITLE
Error in gem installation remit 

### ISSUE THREAD

**Issue by sonianand11** [tylerhunt/remit#8]
When I am trying to install this gem I got this error.

C:\1 My Data>gem install remit
Building native extensions.  This could take a while...
ERROR:  Error installing remit:
        ERROR: Failed to build gem native extension.

```
    C:/Ruby192/bin/ruby.exe extconf.rb
```

checking for stdio.h... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby192/bin/ruby
C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:368:in `try_do': The complier failed to genera
te an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:452:in`try_cpp'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:834:in `block in have_header'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:693:in`block in checking_for'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:280:in `block (2 levels) in postp
one'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:254:in`open'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:280:in `block in postpone'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:254:in`open'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:276:in `postpone'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:692:in`checking_for'
        from C:/Ruby192/lib/ruby/1.9.1/mkmf.rb:833:in `have_header'
        from extconf.rb:2:in`<main>'

Gem files will remain installed in C:/Ruby192/lib/ruby/gems/1.9.1/gems/hpricot-0
.8.4 for inspection.
Results logged to C:/Ruby192/lib/ruby/gems/1.9.1/gems/hpricot-0.8.4/ext/fast_xs/
gem_make.out

What should i do for that?

**Comment by tylerhunt** [comment]
It looks like the failure is actually occurring during the installation of one of Remit's dependencies, Hpricot.

What version of Windows are you on? Maybe this tip will help: http://www.continuousgreg.com/blog/?p=38

**Comment by sonianand11** [comment]
Thank you!!!

Have successfully installed the gem
